### PR TITLE
This seems to work better

### PR DESCRIPTION
**Pull request by philstopford**
The previous code seemed to always be stuck in single color mode.

### CODE REVIEW

**Comment by maniac103** [comment]
Can you provide your config file?

**Comment by philstopford** [comment]
```
[Color]
# Use only Color1 for the whole keyboard
SingleColorOnly = no
Color1 = 0xff0000
Color2 = 0xffff00
Color3 = 0x00ffff
Color4 = 0xff00ff
# Valid modes: solid, pulse, wave_left, wave_right, color_fade
Mode = solid
# Only valid in non-solid mode
Speed = 1

[Brightness]
Current = 2
LastOnValue = 2

```

**Comment by philstopford** [comment]
I also tried commenting out 'SingleColorOnly = yes' and that would not exit single color mode.

**Comment by maniac103** [comment]
Hmm, 'no' in config should evaluate to `False`. If your patch makes any difference, the program should have crashed before. Did it? If so, what's the exception thrown?

(FWIW, I'm using single color mode myself; it seems to work just fine for me)

**Comment by philstopford** [comment]
I didn't get any exception. The program did not crash - it just set the first color defined to all zones.

**Comment by maniac103** [comment]
Totally forgot about this. I could reproduce locally, I wonder why this worked for me earlier. Maybe earlier versions of `configobj` behaved differently.
I've fixed this now, but with a slightly different solution in code.

**Pull request closed without merging**
